
# Common settings
NUMBER_TOPICS = 10
NUMBER_WORDS = 20
RESULTS_FILE_PATH = './results'

# LDA settings
LDA_RESULTS_FILE_PATH = RESULTS_FILE_PATH + '/LDA'


# RTM settings
EPS = 1e-20
RTM_MAX_ITER = 100
RTM_ALPHA = 0.5
RTM_RHO = 1000
RTM_RESULTS_FILE_PATH = RESULTS_FILE_PATH + '/RTM'
